import { access, appendFile, mkdir, readFile, writeFile } from "node:fs/promises"
import type { Plugin } from "@opencode-ai/plugin"
import { join, resolve } from "node:path"

const LOG_HEADER =
  "# AI Work Log\n\nLightweight automatic session entries generated by plugins.\n"
const AUTLOG_MIN_INTERVAL_MS = 10 * 60 * 1000
const AUTLOG_STATE_DIR = join(process.env.HOME || "", ".config", "opencode", "logs")
const AUTLOG_STATE_FILE = join(AUTLOG_STATE_DIR, "project-docs-autolog-state.json")

const buildIdleEntry = (timestampUtc: string): string =>
  `\n- timestamp: ${timestampUtc}\n  source: project-docs-autolog\n  status: idle\n  note: Session reached idle state\n`

const asString = (value: unknown): string | undefined =>
  typeof value === "string" && value.trim().length > 0 ? value.trim() : undefined

const getEventName = (payload: unknown): string | undefined => {
  if (!payload || typeof payload !== "object") return undefined

  const record = payload as Record<string, unknown>
  return asString(record.event) ?? asString(record.name) ?? asString(record.type)
}

const getContext = (payload: unknown): Record<string, unknown> => {
  if (!payload || typeof payload !== "object") return {}

  const record = payload as Record<string, unknown>
  const context = record.context ?? record.ctx
  return context && typeof context === "object"
    ? (context as Record<string, unknown>)
    : {}
}

const getProjectRoot = (context: Record<string, unknown>): string | undefined =>
  asString(context.worktree) ?? asString(context.directory) ?? asString(context.cwd)

const pathExists = async (path: string): Promise<boolean> => {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

const ensureSessionsFile = async (sessionsFile: string): Promise<void> => {
  if (await pathExists(sessionsFile)) return

  try {
    await writeFile(sessionsFile, LOG_HEADER, { flag: "wx" })
  } catch {
    // Silent by design: avoid hard failures in plugin lifecycle.
  }
}

const readAutologState = async (): Promise<Record<string, number>> => {
  try {
    const raw = await readFile(AUTLOG_STATE_FILE, { encoding: "utf8" })
    const parsed = JSON.parse(raw)
    if (!parsed || typeof parsed !== "object") return {}

    const state: Record<string, number> = {}
    for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (typeof key !== "string") continue
      if (typeof value !== "number" || !Number.isFinite(value)) continue
      state[key] = value
    }

    return state
  } catch {
    return {}
  }
}

const writeAutologState = async (state: Record<string, number>): Promise<void> => {
  try {
    await mkdir(AUTLOG_STATE_DIR, { recursive: true })
    await writeFile(AUTLOG_STATE_FILE, `${JSON.stringify(state, null, 2)}\n`, {
      encoding: "utf8",
    })
  } catch {
    // Silent by design: avoid hard failures in plugin lifecycle.
  }
}

export const ProjectDocsAutologPlugin: Plugin = async () => {
  return {
    event: async (input, output) => {
      try {
        const eventName = getEventName(input) ?? getEventName(output)
        if (eventName !== "session.idle") return

        const context = {
          ...getContext(output),
          ...getContext(input),
        }

        const projectRoot = getProjectRoot(context)
        if (!projectRoot) return

        const resolvedRoot = resolve(projectRoot)
        const gitMarker = join(resolvedRoot, ".git")
        if (!(await pathExists(gitMarker))) return

        const docsDir = join(resolvedRoot, "docs", "ai-work")
        const sessionsFile = join(docsDir, "SESSIONS.md")
        const now = Date.now()
        const state = await readAutologState()
        const last = state[resolvedRoot] || 0

        // Throttle repeated session.idle events to avoid noisy/spammy log entries.
        if (now - last < AUTLOG_MIN_INTERVAL_MS) return

        await mkdir(docsDir, { recursive: true })
        await ensureSessionsFile(sessionsFile)
        await appendFile(sessionsFile, buildIdleEntry(new Date().toISOString()), {
          encoding: "utf8",
        })

        state[resolvedRoot] = now
        await writeAutologState(state)
      } catch {
        // Silent by design: plugin must never throw hard errors.
      }
    },
  }
}
