import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Generate a structured Markdown report from provided data. Supports multiple report types: analysis, summary, comparison, and research.",
  args: {
    title: tool.schema.string().describe("Report title"),
    type: tool.schema
      .enum(["analysis", "summary", "comparison", "research"])
      .describe("Type of report to generate"),
    data: tool.schema
      .string()
      .describe(
        "Data or findings to include in the report (can be JSON, text, or structured data)",
      ),
    sections: tool.schema
      .array(tool.schema.string())
      .optional()
      .describe(
        "Specific sections to include. Default: all sections for the report type",
      ),
  },
  async execute(args) {
    const timestamp = new Date().toISOString().split("T")[0]
    const sections: string[] = args.sections ?? []

    const templates: Record<string, string[]> = {
      analysis: [
        "Executive Summary",
        "Key Findings",
        "Data Analysis",
        "Trends & Patterns",
        "Recommendations",
        "Appendix",
      ],
      summary: ["Overview", "Key Points", "Action Items", "Next Steps"],
      comparison: [
        "Overview",
        "Comparison Criteria",
        "Detailed Comparison",
        "Strengths & Weaknesses",
        "Recommendation",
      ],
      research: [
        "Research Questions",
        "Methodology",
        "Findings",
        "Evidence Summary",
        "Conclusions",
        "Research Gaps",
      ],
    }

    const reportSections =
      sections.length > 0 ? sections : (templates[args.type] ?? templates.analysis)

    let report = `# ${args.title}\n\n`
    report += `*Generated: ${timestamp} | Type: ${args.type}*\n\n---\n\n`

    for (const section of reportSections) {
      report += `## ${section}\n\n`

      if (section === "Executive Summary" || section === "Overview") {
        report += `[Summary of key findings and main takeaways]\n\n`
      } else if (section === "Key Findings" || section === "Key Points") {
        report += `- [Finding 1]\n- [Finding 2]\n- [Finding 3]\n\n`
      } else if (section === "Data Analysis") {
        report += `| Metric | Value | Notes |\n|--------|-------|-------|\n| ...    | ...   | ...   |\n\n`
      } else if (section === "Recommendations" || section === "Recommendation") {
        report += `1. [Recommendation 1]\n2. [Recommendation 2]\n3. [Recommendation 3]\n\n`
      } else if (section === "Strengths & Weaknesses") {
        report += `### Strengths\n- [Strength 1]\n\n### Weaknesses\n- [Weakness 1]\n\n`
      } else if (section === "Methodology") {
        report += `- Data sources: [list]\n- Analysis methods: [list]\n- Time period: [dates]\n\n`
      } else if (section === "Research Gaps") {
        report += `- [Gap 1]: [description]\n- [Gap 2]: [description]\n\n`
      } else {
        report += `[Content for this section]\n\n`
      }
    }

    report += `---\n\n*Report generated by OpenCode agent system*\n`

    return report
  },
})
