import { tool } from "@opencode-ai/plugin"
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "fs"
import { join, dirname } from "path"

function slugify(input: string): string {
  const slug = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")

  return slug || "change"
}

function ensureDir(path: string): void {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true })
  }
}

function appendIfMissingHeader(filePath: string, header: string): string {
  let existing = ""
  if (existsSync(filePath)) {
    existing = readFileSync(filePath, "utf-8")
  }

  const headerTitle = header.split("\n")[0]
  if (!existing.includes(headerTitle)) {
    return header
  }

  return existing
}

function writeIfMissing(filePath: string, content: string): boolean {
  if (existsSync(filePath)) {
    return false
  }

  ensureDir(dirname(filePath))
  writeFileSync(filePath, content, "utf-8")
  return true
}

function ensureChangeNotesFile(projectDir: string, changeSlug: string): string {
  const docsDir = join(projectDir, "docs", "ai-work")
  const slug = slugify(changeSlug)
  const notesFile = join(docsDir, "changes", slug, "notes.md")

  writeIfMissing(
    notesFile,
    `# Notes — ${slug}\n\n## Session Notes\n- [${new Date().toISOString().split("T")[0]}] Initialized change.\n`,
  )

  return notesFile
}

interface SessionEntry {
  date: string
  agent: string
  task: string
  summary: string
  files_changed: string[]
  decisions: string[]
  status: "success" | "partial" | "failed"
}

interface DecisionEntry {
  date: string
  title: string
  context: string
  decision: string
  rationale: string
  alternatives_considered: string[]
  files_affected: string[]
}

export const log_session = tool({
  description: "Log a completed work session to the project's AI work documentation. Creates or updates docs/ai-work/SESSIONS.md.",
  args: {
    task: tool.schema.string().describe("Short description of what was accomplished"),
    agent: tool.schema.string().optional().default("opencode-agent").describe("Which agent performed the work"),
    summary: tool.schema.string().describe("Detailed summary of what was done"),
    files_changed: tool.schema.array(tool.schema.string()).optional().describe("List of files created or modified"),
    decisions: tool.schema.array(tool.schema.string()).optional().describe("Key decisions made during this session"),
    status: tool.schema.enum(["success", "partial", "failed"]).optional().default("success").describe("Outcome of the session"),
    change_slug: tool.schema.string().optional().describe("Optional change slug under docs/ai-work/changes/<slug>"),
    change_note: tool.schema.string().optional().describe("Optional extra note for change notes.md"),
  },
  async execute(args, context) {
    const projectDir = context.directory || process.cwd()
    const docsDir = join(projectDir, "docs", "ai-work")

    ensureDir(docsDir)

    const sessionsFile = join(docsDir, "SESSIONS.md")
    const date = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC"

    const entry = `## ${date} — ${args.task}\n\n` +
      `- **Agent**: ${args.agent}\n` +
      `- **Status**: ${args.status}\n` +
      `- **Summary**: ${args.summary}\n` +
      (args.files_changed && args.files_changed.length > 0
        ? `- **Files changed**:\n${args.files_changed.map((f: string) => `  - \`${f}\``).join("\n")}\n`
        : "") +
      (args.decisions && args.decisions.length > 0
        ? `- **Key decisions**:\n${args.decisions.map((d: string) => `  - ${d}`).join("\n")}\n`
        : "") +
      `\n---\n\n`

    let existing = appendIfMissingHeader(
      sessionsFile,
      `# AI Work Log\n\n> Auto-generated by OpenCode agent system. Do not edit manually.\n\n---\n\n`,
    )

    writeFileSync(sessionsFile, existing + entry, "utf-8")

    if (args.change_slug) {
      const notesFile = ensureChangeNotesFile(projectDir, args.change_slug)
      const noteTime = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC"
      const noteEntry = `- [${noteTime}] **${args.task}** — ${args.summary}${args.change_note ? ` (${args.change_note})` : ""}\n`
      const notesExisting = existsSync(notesFile) ? readFileSync(notesFile, "utf-8") : ""
      writeFileSync(notesFile, notesExisting + noteEntry, "utf-8")
    }

    return JSON.stringify({ status: "logged", file: `docs/ai-work/SESSIONS.md`, task: args.task })
  },
})

export const log_decision = tool({
  description: "Log an architectural or design decision to the project's AI work documentation. Creates or updates docs/ai-work/DECISIONS.md.",
  args: {
    title: tool.schema.string().describe("Short title for the decision"),
    context: tool.schema.string().describe("What situation or problem prompted this decision"),
    decision: tool.schema.string().describe("What was decided"),
    rationale: tool.schema.string().describe("Why this decision was made"),
    alternatives: tool.schema.array(tool.schema.string()).optional().describe("Alternative options that were considered but rejected"),
    files_affected: tool.schema.array(tool.schema.string()).optional().describe("Files impacted by this decision"),
    change_slug: tool.schema.string().optional().describe("Optional change slug under docs/ai-work/changes/<slug>"),
  },
  async execute(args, context) {
    const projectDir = context.directory || process.cwd()
    const docsDir = join(projectDir, "docs", "ai-work")

    ensureDir(docsDir)

    const decisionsFile = join(docsDir, "DECISIONS.md")
    const date = new Date().toISOString().split("T")[0]

    const entry = `## [${date}] ${args.title}\n\n` +
      `**Context**: ${args.context}\n\n` +
      `**Decision**: ${args.decision}\n\n` +
      `**Rationale**: ${args.rationale}\n\n` +
      (args.alternatives && args.alternatives.length > 0
        ? `**Alternatives considered**:\n${args.alternatives.map((a: string) => `- ${a}`).join("\n")}\n\n`
        : "") +
      (args.files_affected && args.files_affected.length > 0
        ? `**Files affected**: ${args.files_affected.map((f: string) => `\`${f}\``).join(", ")}\n\n`
        : "") +
      `---\n\n`

    let existing = appendIfMissingHeader(
      decisionsFile,
      `# Architecture Decisions\n\n> Auto-generated by OpenCode agent system. Records significant architectural and design decisions made during AI-assisted development.\n\n---\n\n`,
    )

    writeFileSync(decisionsFile, existing + entry, "utf-8")

    if (args.change_slug) {
      const notesFile = ensureChangeNotesFile(projectDir, args.change_slug)
      const noteTime = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC"
      const rationaleSummary = args.rationale.length > 180 ? `${args.rationale.substring(0, 177)}...` : args.rationale
      const noteEntry = `- [${noteTime}] **Decision: ${args.title}** — ${args.decision} (Rationale: ${rationaleSummary})\n`
      const notesExisting = existsSync(notesFile) ? readFileSync(notesFile, "utf-8") : ""
      writeFileSync(notesFile, notesExisting + noteEntry, "utf-8")
    }

    return JSON.stringify({ status: "logged", file: `docs/ai-work/DECISIONS.md`, title: args.title })
  },
})

export const init_change = tool({
  description: "Initialize a structured per-change documentation folder under docs/ai-work/changes/<slug>.",
  args: {
    slug: tool.schema.string().describe("Change identifier (e.g. auth-refactor)"),
    title: tool.schema.string().describe("Human-readable title"),
    summary: tool.schema.string().describe("Short goal summary for the change"),
    kind: tool.schema.enum(["feature", "bugfix", "refactor", "docs", "research", "chore"]).describe("Type of change"),
  },
  async execute(args, context) {
    const projectDir = context.directory || process.cwd()
    const docsDir = join(projectDir, "docs", "ai-work")
    const slug = slugify(args.slug)
    const changeDir = join(docsDir, "changes", slug)

    ensureDir(changeDir)

    const today = new Date().toISOString().split("T")[0]
    const templates: Record<string, string> = {
      "spec.md": `# Spec — ${args.title}\n\n- **Slug**: ${slug}\n- **Kind**: ${args.kind}\n- **Summary**: ${args.summary}\n\n## Problem\n[Describe the problem]\n\n## Scope\n[In scope / out of scope]\n\n## Acceptance Criteria\n- [ ] ...\n`,
      "tasks.md": `# Tasks — ${args.title}\n\n## Checklist\n- [ ] Task 1\n- [ ] Task 2\n\n## Dependencies\n- None\n`,
      "verify.md": `# Verify — ${args.title}\n\n## Validation Steps\n- [ ] Tests executed\n- [ ] Manual checks completed\n\n## Result\n- Status: pending\n- Notes:\n`,
      "notes.md": `# Notes — ${args.title}\n\n## Session Notes\n- [${today}] Initialized change.\n`,
    }

    const created_files: string[] = []
    const existing_files: string[] = []

    for (const [name, content] of Object.entries(templates)) {
      const filePath = join(changeDir, name)
      const relativePath = join("docs", "ai-work", "changes", slug, name)
      const created = writeIfMissing(filePath, content)
      if (created) {
        created_files.push(relativePath)
      } else {
        existing_files.push(relativePath)
      }
    }

    return JSON.stringify({
      status: "initialized",
      slug,
      path: join("docs", "ai-work", "changes", slug),
      created_files,
      existing_files,
    })
  },
})

export const list_changes = tool({
  description: "List structured change folders under docs/ai-work/changes/.",
  args: {
    project_dir: tool.schema.string().optional().describe("Optional explicit project root directory"),
  },
  async execute(args, context) {
    const projectDir = args.project_dir || context.directory || process.cwd()
    const changesDir = join(projectDir, "docs", "ai-work", "changes")

    if (!existsSync(changesDir)) {
      return JSON.stringify({ changes: [] })
    }

    const entries = readdirSync(changesDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const slug = entry.name
        const basePath = join(changesDir, slug)
        return {
          slug,
          path: join("docs", "ai-work", "changes", slug),
          hasSpec: existsSync(join(basePath, "spec.md")),
          hasTasks: existsSync(join(basePath, "tasks.md")),
          hasVerify: existsSync(join(basePath, "verify.md")),
          hasNotes: existsSync(join(basePath, "notes.md")),
        }
      })

    return JSON.stringify({ changes: entries })
  },
})

export const generate_context = tool({
  description: "Generate or update the project context summary. Creates docs/ai-work/CONTEXT.md with a high-level overview of the project state.",
  args: {
    project_name: tool.schema.string().describe("Name of the project"),
    description: tool.schema.string().describe("What this project does"),
    tech_stack: tool.schema.array(tool.schema.string()).describe("Technologies, frameworks, and libraries used"),
    architecture: tool.schema.string().describe("Brief description of the architecture"),
    key_patterns: tool.schema.array(tool.schema.string()).optional().describe("Important patterns or conventions in this project"),
    current_focus: tool.schema.string().optional().describe("What is currently being worked on"),
  },
  async execute(args, context) {
    const projectDir = context.directory || process.cwd()
    const docsDir = join(projectDir, "docs", "ai-work")

    ensureDir(docsDir)

    const date = new Date().toISOString().split("T")[0]
    const content = `# Project Context: ${args.project_name}\n\n` +
      `> Last updated: ${date}\n\n` +
      `## What This Project Does\n\n${args.description}\n\n` +
      `## Tech Stack\n\n${args.tech_stack.map((t: string) => `- ${t}`).join("\n")}\n\n` +
      `## Architecture\n\n${args.architecture}\n\n` +
      (args.key_patterns && args.key_patterns.length > 0
        ? `## Key Patterns & Conventions\n\n${args.key_patterns.map((p: string) => `- ${p}`).join("\n")}\n\n`
        : "") +
      (args.current_focus
        ? `## Current Focus\n\n${args.current_focus}\n\n`
        : "") +
      `---\n\n*This file is auto-generated by the OpenCode agent system. Update it when the project context changes significantly.*\n`

    writeFileSync(join(docsDir, "CONTEXT.md"), content, "utf-8")
    return JSON.stringify({ status: "generated", file: `docs/ai-work/CONTEXT.md`, project: args.project_name })
  },
})
